version: '3'

services:
  book-my-show-app:
    container_name: book-my-show
    restart: always
    build:
      context: .
      dockerfile: debug.Dockerfile
    ports:
      - 8000:8080
      - 8081:8081
    expose:
      - 8000
      - 8081
      - 8080
    depends_on:
      - book-my-show-db
    networks:
      book-my-show-network:
    environment:
      - MYSQL_DATABASE=${MYSQL__DATABASE}
      - DB_HOST=${DB__HOST}
      - DB_PORT=${DB__PORT}
      - MYSQL_ROOT_USERNAME=${MYSQL__ROOT__USERNAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL__ROOT__PASSWORD}
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8081 -Djava.security.egd=file:/dev/./urandom -jar /app.jar

  book-my-show-db:
    container_name: book-my-show-db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - book-my-show-db-volume:/var/lib/mysql
    networks:
      book-my-show-network:
    environment:
      - MYSQL_DATABASE=${MYSQL__DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL__ROOT__PASSWORD}

volumes:
  book-my-show-db-volume:

networks:
  book-my-show-network:
    driver: bridge
